[openai]
model = "gpt-3.5-turbo-16k"
max-tokens = 16384
api-key = "YOUR_API_KEY"

[openai.role.system]
statement = "For each following propmt, a markdown document will be give. Extract the `title`, `author`, and suggest a short `blurb` from this. Present this as JSON - minimized without newlines, where the keys are lowercase. With no extra characters, words, or padding."